version: "3"

services:
  postgres:
    image: postgres:15.2
    restart: unless-stopped
    ports:
        - 5433:5432
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: changeme
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    networks:
       - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    depends_on:
      - postgres
    restart: unless-stopped


volumes:
    postgres:
    pgadmin:

networks:
  postgres:
    driver: bridge